default_language_version:
  python: python3.9
fail_fast: true
exclude: "egg-info"

repos:
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        exclude: "docs"
        additional_dependencies:
          - flake8-bugbear==22.4.25
          - flake8-comprehensions==3.10.0
          - flake8-mutable==1.2.0
          - flake8-print==5.0.0
          - flake8-quotes==3.3.1
          - flake8-simplify==0.19.2
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-toml
      - id: check-yaml
        exclude: "tests"
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: mixed-line-ending
      - id: trailing-whitespace
      - id: debug-statements
      - id: requirements-txt-fixer
      - id: check-added-large-files
      - id: name-tests-test
        args: [--django]
        exclude: "helpers"
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.9.0
    hooks:
      - id: python-check-mock-methods
      - id: python-no-eval
      - id: python-no-log-warn
      - id: text-unicode-replacement-char
  - repo: local
    hooks:
      - id: wrong-pytest-imports
        name: wrong pytest imports
        language: pygrep
        entry: ^from _pytest
        types: [python]
